core/blog/urls.py
from django.urls import path,re_path,include
from . import views
app_name = 'blog'
urlpatterns = [
    re_path(r'^$',views.post_view.as_view(),name='index'),
    path("category/<str:slug>/",views.CategoryList.as_view(),name='category'),
    path("tag/<str:slug>/",views.TagList.as_view(),name='tag'),
    re_path(r'^success/$',views.success.as_view(),name='success'),
    path("<str:slug>",views.post_detail.as_view(),name='detail'),
    path('api/',include('blog.api.api_urls')),
    path('search/',views.SearchList.as_view(),name='search'),

]

core/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.urls.conf import re_path
from rest_framework_simplejwt.views import TokenObtainPairView,TokenRefreshView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls'),name='blog'),
    path('forum/',include('forum.urls'),name='forum'),
    path('shop/',include('shop.urls'),name='shop'),
    path('',include('mysite.urls')),
    path('api-auth/', include('rest_framework.urls')),
    re_path(r'^ckeditor/$', include('ckeditor_uploader.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]
urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL , document_root = settings.MEDIA_ROOT)

core/media/templates/share/last_post_cat.html
<!-- product_list part start-->
<section class="product_list best_seller section_padding">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="section_tittle text-center">
                    <h2>Most Favorite <span>Post</span></h2>
                </div>
            </div>
        </div>

        <div class="row align-items-center justify-content-between">
            
            <div class="col-lg-12">
                <div class="best_product_slider owl-carousel">
                    {% for post  in last_post %}


                    <div class="single_product_item">
                        {% if post.image %}
                          
                        <img src="{{ post.image.url }}" alt="">
                        {% endif %}
                        <div class="single_product_text">
                            <h4>{{post.title}}</h4>
                            <div class="media-body">
                                {% for username in post.authors.all %}

                                <h3>Authors : {{username.username}}</h3>

                                {% endfor %}

                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
</section>
<!-- product_list part end-->

core/media/templates/share/most_post_cat.html
<!-- product_list part start-->
<section class="product_list best_seller section_padding">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="section_tittle text-center">
                    <h2>Last Favorite <span>Post</span></h2>
                </div>
            </div>
        </div>

        <div class="row align-items-center justify-content-between">
            
            <div class="col-lg-12">
                <div class="best_product_slider owl-carousel">
                    {% for post  in most_post %}


                    <div class="single_product_item">
                        {% if post.image %}
                          
                        <img src="{{ post.image.url }}" alt="">
                        {% endif %}
                        <div class="single_product_text">
                            <h4>{{post.title}}</h4>
                            <div class="media-body">
                                {% for username in post.authors.all %}

                                <h3>Authors : {{username.username}}</h3>

                                {% endfor %}

                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
</section>
<!-- product_list part end-->

core/media/templates/share/navbar_cat.html
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="./blog" id="navbarDropdown_1"
        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Category
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
        {% for cat  in category %}
          
        <a class="dropdown-item" href="{% url 'blog:category' cat.slug %}" class="d-flex">
            {{cat.title}}

        </a>
        
        {% endfor %}
        
    </div>
</li>

core/media/templates/share/product_cat.html
    <!-- product_list start-->
    <section class="product_list section_padding">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="section_tittle text-center">
                        <h2>awesome <span>shop</span></h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="product_list_slider owl-carousel">
                        <div class="single_product_list_slider">
                            <div class="row align-items-center justify-content-between">
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="single_product_list_slider">
                            <div class="row align-items-center justify-content-between">
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="single_product_item">
                                        <img src="" alt="">
                                        <div class="single_product_text">
                                            <h4>Quartz Belt Watch</h4>
                                            <h3>$150.00</h3>
                                            <a href="#" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- product_list part start-->

core/media/templates/share/product_category_cat.html
<aside class="left_widgets p_filter_widgets">
    <div class="l_w_title">
        <h3>Browse Categories</h3>
    </div>
    {% for cat in category %}
    <div class="widgets_inner">
        <ul class="list">
            <li>
                <a href="#">{{cat.title}}</a>
                <span>{{cat.count}}</span>
            </li>
        </ul>
    </div>
    {% endfor %}
</aside>

core/media/templates/share/rating_tag.html
{% load static %}
<div class="row">
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   
    <div class="col text-center">
        <form class="rate-form" action="" method="POST" id="{{object.id}}">
            {% csrf_token %}
            <button type="submit" class="fa fa-star fa-3x my-btn" id="first"></button>
            <button type="submit" class="fa fa-star fa-3x my-btn" id="second"></button>
            <button type="submit" class="fa fa-star fa-3x my-btn" id="third"></button>
            <button type="submit" class="fa fa-star fa-3x my-btn" id="fourth"></button>
            <button type="submit" class="fa fa-star fa-3x my-btn" id="fifth"></button>
        </form>
        <br>
        <div id="confirm-box"></div>
    </div>
    
</div>
<script src="{% static 'js/rating.js'%}"></script>

core/media/templates/share/recent_post_cat.html
<aside class="single_sidebar_widget popular_post_widget">
    <h3 class="widget_title">Recent Post</h3>
    {% for cat  in recent_post %}
    <div class="media post_item">
        <img src="{{cat.image.url}}" width="20%" alt="post">
        <div class="media-body">
            <a href="./{{cat.uid}}">
                <h3>{{cat.title}}</h3>
            </a>
            <p>{{cat.create}}</p>
        </div>
    </div>
    {% endfor %}

</aside>

core/media/templates/share/search_tag.html
<form method="GET">
    {{filter.form}}
    <button type="submit" class="btn">submit</button>

</form>

<ul>
    {% for  result in filter.qs %}
      <li>
          <a href="#"> {{result}}</a>
      </li>
    {% endfor %}
</ul>

core/media/templates/share/slider_cat.html
<section class="banner_part">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <div class="banner_slider owl-carousel">
               
                    {% for slide  in slider %}
               
                    <div class="single_banner_slider">
                        <div class="row">
                            <div class="col-lg-5 col-md-8">
                                <div class="banner_text">
                                    <div class="banner_text_iner">
                                        <h1>{{slide.image.title}}</h1>
                                        <p>{{slide.image.description}}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="banner_img d-none d-lg-block">
                                <img src="{{slide.image.image.url}}" alt="">
                            </div>
                        </div>
                    </div>
                

                {% endfor %}
                <!-- <div class="single_banner_slider">
                        <div class="row">
                            <div class="col-lg-5 col-md-8">
                                <div class="banner_text">
                                    <div class="banner_text_iner">
                                        <h1>Cloth $ Wood Sofa</h1>
                                        <p>Incididunt ut labore et dolore magna aliqua quis ipsum
                                            suspendisse ultrices gravida. Risus commodo viverra</p>
                                        <a href="#" class="btn_2">buy now</a>
                                    </div>
                                </div>
                            </div>
                            <div class="banner_img d-none d-lg-block">
                                <img src="img/banner_img.png" alt="">
                            </div>
                        </div>
                    </div> -->
            </div>
            <div class="slider-counter"></div>
        </div>
    </div>
    
</section>

core/media/templates/share/tag_clouds_cat.html
<aside class="single_sidebar_widget tag_cloud_widget">
    <h4 class="widget_title">Tag Clouds</h4>
    <ul class="list">
        {% for cat in tag_clouds %}
        <li>
            <a href="./tag/{{cat.slug}}/">{{cat.title}}</a>
        </li>
          
        {% endfor %}
    </ul>
</aside>

core/media/templates/share/temp.html
{% load static %}
{% load base_tag %}
<!doctype html>
<html lang="zxx">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{%title%}</title>

    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <!-- animate CSS -->        
    <link rel="stylesheet" href="{% static 'css/animate.css'%}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css'%}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css'%}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!-- start rating  -->


</head>

<body>
    <!--::header part start::-->
    
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="index.html"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"><i class="fas fa-bars"></i></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="/">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/blog/">Blog</a>
                                </li>
                            {%category_navbar%}
                                
                                <li class="nav-item">
                                    <a class="nav-link" href="/contact">Contact</a>
                                </li>
                            </ul>
                        </div>
                        <div class="hearer_icon d-flex">
                          
                            <form action="{% url 'blog:search' %}" method="GET" class="input-group">
                            
                                <input type="search" class="form-control"  name="query" value="{{request.GET.q}}" id="">
                                
                                <button class="btn input-group-addon" type="submit"> <i class="ti-search"></i></button>
                            
                            </form>
                            <a href=""><i class="ti-heart"></i></a>
                            <div class="dropdown cart">
                                <a class="dropdown-toggle" href="#" id="navbarDropdown3" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="ti-bag"></i>
                                </a>
                                <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <div class="single_product">
    
                                    </div>
                                </div> -->
                                
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
       
    </header>
    <!-- Header part end-->

    <section class="feature_part padding_top">
        {% block body %}



        {% endblock %}
    </section>
    <!--::footer_part start::-->
    <footer class="footer_part">
        <div class="container">
            <div class="row justify-content-around">
                <div class="col-sm-6 col-lg-2">
                    <div class="single_footer_part">
                        <h4>Top Products</h4>
                        <ul class="list-unstyled">
                            <li><a href="">Managed Website</a></li>
                            <li><a href="">Manage Reputation</a></li>
                            <li><a href="">Power Tools</a></li>
                            <li><a href="">Marketing Service</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-2">
                    <div class="single_footer_part">
                        <h4>Quick Links</h4>
                        <ul class="list-unstyled">
                            <li><a href="">Jobs</a></li>
                            <li><a href="">Brand Assets</a></li>
                            <li><a href="">Investor Relations</a></li>
                            <li><a href="">Terms of Service</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-2">
                    <div class="single_footer_part">
                        <h4>Features</h4>
                        <ul class="list-unstyled">
                            <li><a href="">Jobs</a></li>
                            <li><a href="">Brand Assets</a></li>
                            <li><a href="">Investor Relations</a></li>
                            <li><a href="">Terms of Service</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-2">
                    <div class="single_footer_part">
                        <h4>Resources</h4>
                        <ul class="list-unstyled">
                            <li><a href="">Guides</a></li>
                            <li><a href="">Research</a></li>
                            <li><a href="">Experts</a></li>
                            <li><a href="">Agencies</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-4">
                    <div class="single_footer_part">
                        <h4>Newsletter</h4>
                        <p>Heaven fruitful doesn't over lesser in days. Appear creeping
                        </p>
                        <div id="mc_embed_signup">
                            <form target="_blank"
                                action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                method="get" class="subscribe_form relative mail_part">
                                <input type="email" name="email" id="newsletter-form-email" placeholder="Email Address"
                                    class="placeholder hide-on-focus" onfocus="this.placeholder = ''"
                                    onblur="this.placeholder = ' Email Address '">
                                <button type="submit" name="submit" id="newsletter-submit"
                                    class="email_icon newsletter-submit button-contactForm">subscribe</button>
                                <div class="mt-10 info"></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
     
    </footer>
    <!--::footer_part end::-->

    <!-- jquery plugins here-->
    <script src="{% static 'js/jquery-3.3.1.slim.min.js'%}"></script>
    <!-- popper js -->
    <script src="{% static 'js/popper.min.js'%}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <!-- easing js -->
    <script src="{% static 'js/jquery.magnific-popup.js'%}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/swiper.min.js'%}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/masonry.pkgd.js'%}"></script>
    <!-- particles js -->
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js'%}"></script>
    <!-- slick js -->
    <script src="{% static 'js/slick.min.js'%}"></script>
    <script src="{% static 'js/jquery.counterup.min.js'%}"></script>

    <script src="{% static 'js/contact.js'%}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js'%}"></script>
    <script src="{% static 'js/jquery.form.js'%}"></script>
    <script src="{% static 'js/jquery.validate.min.js'%}"></script>
    <script src="{% static 'js/mail-script.js'%}"></script>
    <!-- custom js -->
    <script src="{% static 'js/custom.js'%}"></script>
    <!-- star rating  -->

</body>

</html>