core/blog/urls.py
from django.urls import path,re_path,include
from . import views
app_name = 'blog'
urlpatterns = [
    re_path(r'^$',views.post_view.as_view(),name='index'),
    path("category/<str:slug>/",views.CategoryList.as_view(),name='category'),
    path("tag/<str:slug>/",views.TagList.as_view(),name='tag'),
    re_path(r'^success/$',views.success.as_view(),name='success'),
    path("<str:slug>",views.post_detail.as_view(),name='detail'),
    path('api/',include('blog.api.api_urls')),
    path('search/',views.SearchList.as_view(),name='search'),

]

core/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.urls.conf import re_path
from rest_framework_simplejwt.views import TokenObtainPairView,TokenRefreshView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls'),name='blog'),
    path('forum/',include('forum.urls'),name='forum'),
    path('shop/',include('shop.urls'),name='shop'),
    path('',include('mysite.urls')),
    path('api-auth/', include('rest_framework.urls')),
    re_path(r'^ckeditor/$', include('ckeditor_uploader.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]
urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL , document_root = settings.MEDIA_ROOT)

core/shop/urls.py
from django.urls import path,include
from . import views
app_name = 'shop'
urlpatterns = [
path('',views.Allproduct.as_view(),name="allproduct"),
path("<str:slug>/",views.ProductList.as_view(),name='detail'),
path("category/<str:slug>/",views.CategoryList.as_view(),name='category'),
path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
path('api/',include('shop.api.api_urls')),
path('order-summary', views.OrderSummaryView.as_view(), name='order-summary'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', views.remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
]

core/shop/models.py
from django.db import models
from .submodels.product import Product
from .submodels.category import Category
from .submodels.address import Address
from .submodels.order import Order
from .submodels.orderItem import OrderItem
from .submodels.coupon import Coupon
# Create your models here.

core/shop/views.py
from django.views.generic import ListView,DetailView,View
from .models import Product,Category,Order,OrderItem,Coupon
from django.shortcuts import render,get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
# Create your views here.
class Allproduct(ListView):
    queryset = Product.objects.available()
    template_name = 'shop/shop.html'
    context_object_name = 'shop'
    paginate_by = 25
    
class ProductList(DetailView):
    queryset = Product.objects.available()
    template_name = 'shop/produce.html'
    context_object_name = 'shop'
    slug_url_kwarg ='slug'

class CategoryList(ListView):
    paginate_by = 5
    template_name = 'shop/shop.html'
    context_object_name = 'product_category'
    model = Product
    def get_queryset(self):
        self.category = get_object_or_404(Category,slug = self.kwargs['slug'])
        product = Product.objects.filter(category = self.category)
        return product
    def get_context_data(self, **kwargs):
        context = super(CategoryList,self).get_context_data(**kwargs)
        context["category"] = self.category
        return context

@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        product=item,
        user=request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0] 
        # check if the order item is in the order
        if order.items.filter(product=item).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item quantity was updated.")
            return redirect("shop:order-summary")
        else:
            order.items.add(order_item)
            messages.info(request, "This item was added to your cart.")
            return redirect("shop:order-summary")
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "This item was added to your cart.")
        return redirect("shop:order-summary")

@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(product=item).exists():
            order_item = OrderItem.objects.filter(
                product=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, "This item was removed from your cart.")
            return redirect("shop:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect('shop:order-summary')
    else:
        messages.info(request, "You do not have an active order")
        return redirect("shop:product", slug=slug)

@login_required
def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)

    order_qs = Order.objects.filter(
        user=request.user
    )

    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order

        if order.items.filter(product=item).exists():
            order_item = OrderItem.objects.filter(
                product=item,

            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, "This item quantity was updated.")
            return redirect("shop:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("shop:order-summary")
    else:
        messages.info(request, "You do not have an active order")
        return redirect("shop:order-summary", slug=slug)

def get_coupon(request, code):
    try:
        coupon = Coupon.objects.get(code=code)
        return coupon
    except ObjectDoesNotExist:
        messages.info(request, "This coupon does not exist")
        return redirect("shop:checkout")

class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'shop/test.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")

core/media/templates/shop/shop.html
    <!--================End Category Product Area =================-->

{% extends 'share/temp.html' %}
{% load static %}
{% load category_tag %}
{% block body %}
    <!-- product_list part start-->
   
    <!--================Home Banner Area =================-->
    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>Shop Category</h2>
                            <p>Home <span>-</span> Shop Category</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <!--================Category Product Area =================-->
    <section class="cat_product_area section_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="left_sidebar_area">
                        {%category%}
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="product_top_bar d-flex justify-content-between align-items-center">
                                <div class="single_product_menu">
                                    <p><span>10000 </span> Prodict Found</p>
                                </div>
                                <div class="single_product_menu d-flex">
                                    <h5>short by : </h5>
                                    <select>
                                        <option data-display="Select">name</option>
                                        <option value="1">price</option>
                                        <option value="2">product</option>
                                    </select>
                                </div>
                                <div class="single_product_menu d-flex">
                                    <h5>show :</h5>
                                    <div class="top_pageniation">
                                        <ul>
                                            <li>1</li>
                                            <li>2</li>
                                            <li>3</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="single_product_menu d-flex">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="search"
                                            aria-describedby="inputGroupPrepend">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroupPrepend"><i
                                                    class="ti-search"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                
                    <div class="row align-items-center latest_product_inner">
                        {% for item in shop %}
  
                  

                        <div class="col-lg-4 col-sm-6">
                            <div class="single_product_item">
                                <img src="img/product/product_1.png" alt="">
                                <div class="single_product_text">
                                    <h4>{{item.title}}</h4>
                                    <h3>{{item.price}}</h3>
                                    <a href="{% url 'shop:add-to-cart' item.slug %}" class="add_cart">+ add to cart<i class="ti-heart"></i></a>
                                </div>
                            </div>
                        </div>

                        {% endfor %}


                        
                        
                        
                        
                        
                        
                        </div>
                        <div class="col-lg-12">
                            <div class="pageination">
                                <nav class="blog-pagination justify-content-center d-flex">

                                    {% if is_paginated %}
                                    <ul class="pagination">
                                      {% if page_obj.has_previous %}
                                        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                      {% else %}
                                        <li class="disabled"><span>&laquo;</span></li>
                                      {% endif %}
                                      {% for i in paginator.page_range %}
                                        {% if page_obj.number == i %}
                                          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                        {% else %}
                                          <li><a href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                      {% endfor %}
                                      {% if page_obj.has_next %}
                                        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                      {% else %}
                                        <li class="disabled"><span>&raquo;</span></li>
                                      {% endif %}
                                    </ul>
                                  {% endif %}
                                    
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Category Product Area =================-->

    <!-- product_list part start-->
    <section class="product_list best_seller">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="section_tittle text-center">
                        <h2>Best Sellers <span>shop</span></h2>
                    </div>
                </div>
            </div>
            <div class="row align-items-center justify-content-between">
                <div class="col-lg-12">
                    <div class="best_product_slider owl-carousel">
                        <div class="single_product_item">
                            <img src="img/product/product_1.png" alt="">
                            <div class="single_product_text">
                                <h4>Quartz Belt Watch</h4>
                                <h3>$150.00</h3>
                            </div>
                        </div>
                        <div class="single_product_item">
                            <img src="img/product/product_2.png" alt="">
                            <div class="single_product_text">
                                <h4>Quartz Belt Watch</h4>
                                <h3>$150.00</h3>
                            </div>
                        </div>
                        <div class="single_product_item">
                            <img src="img/product/product_3.png" alt="">
                            <div class="single_product_text">
                                <h4>Quartz Belt Watch</h4>
                                <h3>$150.00</h3>
                            </div>
                        </div>
                        <div class="single_product_item">
                            <img src="img/product/product_4.png" alt="">
                            <div class="single_product_text">
                                <h4>Quartz Belt Watch</h4>
                                <h3>$150.00</h3>
                            </div>
                        </div>
                        <div class="single_product_item">
                            <img src="img/product/product_5.png" alt="">
                            <div class="single_product_text">
                                <h4>Quartz Belt Watch</h4>
                                <h3>$150.00</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- product_list part end-->

    <!-- product_list part end-->
    {% endblock %}

core/media/templates/shop/test.html
{% extends 'share/temp.html' %}

{% block body %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
       
            <td>{{ order_item.product.title }}</td>
            <td>{{ order_item.product.price }}</td>
            <td>

                <a href="{% url 'shop:remove-single-item-from-cart' order_item.product.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'shop:add-to-cart' order_item.product.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.product.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'shop:remove-single-item-from-cart' order_item.product.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock %}